language: python
sudo: false

python:
  - "3.8"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create -n test_env --file environment.yml
  - source activate test_env
  - conda list
  - which conda
  - which python
  - pip install .
  - python setup.py install --user

script:
  - coverage run --source {{ cookiecutter.project_name.lower().replace(' ', '_') }} -m py.test
  - coverage report

after_success:
  - coveralls
